### PR TITLE
Adapting code to use as modules and no overlap with THREE.* namespace

### PR DESCRIPTION
**Pull request by silviopaganini**
Sending a PR to make it easier to use as a module (check the example/es6 folder), as well as making THREEAR as a separate namespace so we don't have any conflicts with THREE 

also, added Rollup instead of Webpack for building it so we can have 2 targets (UMD and ES6 modules) 

Would be nice to get this merged so we can just npm i three.ar.js

### CODE REVIEW

**Comment by silviopaganini** [comment]
I signed it!

**Comment by jsantell** [comment]
Thanks for the PR @silviopaganini! This is a lot to unpack. What issues were you having that this solves? Is it a problem due to attaching AR* objects to the THREE namespace? Using three as a dependent in a library to function across build environments is difficult, as I'm sure you've experienced. The way around this is to require the consumer's build step to provide it's own THREE global (for flexibility), similar to the rollup global config you've set. I can see that loading three via ES module, and three.ar.js attempting to attach to those globals causing issues. If no longer attaching to the THREE namespace, would doing `import { ... } from 'three.ar.js/src/index'` work in your environment?

I'd like to start a discussion on the specific issues you're having, in what environment, and/or supporting ES modules (although WebARonARCore is built from Chromium 57, which does not have module loading), as I'm generally conservative on changing build systems, and introducing breaking changes. I wonder if adding `externals` to webpack and specifying three as a peer dependency will get us there, and only attaching to THREE global in a traditional <script> environment.

What do you think? Thanks again for starting this!

**Comment by silviopaganini** [comment]
hi there! 

mainly this PR creates a build system similar to three.js, building a modular library and a library with the THREEAR namespace... 

the module library works fine with Webpack, Rollup, Gulp as long as you're using browserify / babel... 

I do understand the point of having THREE as a global dependency in smaller projects, but that doesn't work nicely on larger projects where you have to compile a lot of code and are importing separate modules from threejs, instead of just `import * as THREE from 'three`. The current approach works nicely if you're adding three.js / vr-controls and three.ar.js as a script tag on HTML, but when you try to import those modules, it just breaks since THREE is not available. 

I was checking this Babel preset https://github.com/babel/babel-preset-env and it basically lets you use native es6 module imports if your browser supports it.

Maybe adding THREE as a external peer dependency could work, I haven't tested that.

I just checked the WebARonARCore repo and I don't think I've tested on the latest one, I'll try to test it now... 

If that's interesting to you, maybe we could have this as a separate branch `next` or `es6` ... up to you =)

**Comment by jsantell** [comment]
With 0.1.5 released a few days ago, the current release now [allows importing three.ar.js as an independent module](https://github.com/google-ar/three.ar.js#modules) that uses three as a peerDependency and fixes the issues of appending the three.ar.js objects to the `THREE` global. This does not however export the es6 module format, but I am admittedly not that experienced in using `<script type="module">` -- do dependencies like 'three' get imported from node_modules via the `import ... 'three'` statements? That's what it looks like in the `module` output code from rollup, but can't find any documentation on resolving dependencies like that.

Closing this PR for now, but open to further discussing supporting modules -- I think the 0.1.5 change should get you significantly closer to your goals, but any short comings, let's open up another issue and discuss there. Thank you for the PR and getting this push started!

**Pull request closed without merging**
